spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: org.apache.commons.dbcp.BasicDataSource
        url: jdbc:mysql://192.168.1.101:3306/db0?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
      ds1:
        type: org.apache.commons.dbcp.BasicDataSource
        url: jdbc:mysql://192.168.1.101:3306/ds1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    sharding:
      tables:
        order:
          actual-data-nodes: db$->{0..1}.order->{0..1}
          key-generator:
            colum: order_id #自增列的名称
            type: SNOWFLAKE #自增列值生成器类型，缺省表示使用默认自增列值生成器。可使用用户自定义的列值生成器或选择内置类型：SNOWFLAKE/UUID
          table-strategy:
            inline:
              sharding-column: order_id #分片列名称
              algorithm-expression: order$->{order_id % 2} #分片算法表达式
      binding-tables: order #绑定表规则列表
      broadcast-tables: config #广播表规则列表
logging:
  level:
    org:
      springframework:
        security: INFO