server:
  port: 8080
  servlet:
    session:
      timeout: 6h   #session过期时间，以秒为单位，session过期后security登录会失效 不到1分钟会默认为1分钟
      cookie:
        name: JSESSIONID


spring:
  shardingsphere:
    datasource:
      names: db0,db1
      db0:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.1.100:3306/db0?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
      db1:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.1.100:3306/db1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    sharding:
      tables:
        order:
          actual-data-nodes: db$->{0..1}.order$->{0..1}
          key-generator:
            colum: id #自增列的名称
            type: SNOWFLAKE #自增列值生成器类型，缺省表示使用默认自增列值生成器。可使用用户自定义的列值生成器或选择内置类型：SNOWFLAKE/UUID
          database-strategy:
            inline:
              sharding-column: order_id #分片列名称
              algorithm-expression: order$->{order_id % 2} #分片算法表达式
      binding-tables: order #绑定表规则列表
      broadcast-tables: config #广播表规则列表
  main:
    allow-bean-definition-overriding: true #比较严格，所以呢，需要在配置文件添加一个属性
  application:
    name: sharding-jdbc
  profiles:
    active: local
  thymeleaf:
    cache: false #关闭缓存否则没法看到实时页面
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/resources/ #默认可以不用配置
    suffix: .html #默认可以不用配置
    servlet:
      content-type: text/html
  session:
    store-type: redis #redis管理session
mybatis:
  mapperLocations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  typeAliasesPackage: com.shardingjdbc.model # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true


api:
  boot:
    swagger:
      enable: true
      description: securityAPI文档
      version: 1.0
      license: ApiBoot
      license-url: http://apiboot.minbox.io/zh-cn/
      contact:
        name: QP